### PR TITLE
New Major Release

### PR DESCRIPTION
**Pull request by delofson0211**
- Down sampling
- House keeping
- Variable Type Changes
- build.sh and setup.sh script additions

### CODE REVIEW

**Comment by kkeefe** [comment]
it looks like there was a git add that included a build directory. Is there a way to cherry pick that out? It's not too big, really.
--it looks like the merge of feature/14 included the build directory of RTD

Also, I can't really tell what the downsampling is supposed to be doing. My understanding is that it would affect the possible timing of when resets would occur, but it looks like it helps determine that amount of charge required to cause a reset. Is this accurate?

**Comment by delofson0211** [comment]
@kkeefe yes that has been a sore spot. There should be some way to pull that out, but @kelseymh would probably know best.

The point of down sampling is to just keep the size of samples down, therefore lowering the memory requirements and the processing time (instead of having N electrons, you have c*N big electrons of charge 1/c, where 0 < c <= 1). At more extreme values of c, it will definitely affect the timing of resets, however @Eikenbcr has been going through and ensuring that we understand how it works. I know he will have a good explanation for the group soon. Worst case scenario, it is being implemented as an optional argument, and set by default to c=1 (no down sampling), so it will only be used in extreme cases if the user wants it.

**Comment by kelseymh** [comment]
> Also, I can't really tell what the downsampling is supposed to be doing. My understanding is that it would affect the possible timing of when resets would occur, but it looks like it helps determine that amount of charge required to cause a reset. Is this accurate?

Hi, @kkeefe.  Downsampling is a method of reducing the number of tracks and increasing the processing rate, _without_ (ideally!) altering the timing, or the energy collection, or whatever.  The idea is that instead of tracking all N million individual electrons, you only track, say N/100 of them, and each one you track you assign a _weight_ of 100.  Rather than summing charges in a loop using "++" (i.e., each individual charge causes an increment of 1), you sum the charges using "+= weight".

If the full statistics are large enough, and the individual trackings are statistically independent, then you should get the same average result.  The variance will be different in the downsampled case, just because the statistics are lower.  

The main effort with downsampling is running a bunch of one-time tests where you vary the sampling fraction, and find yourself a good balance between the effect on resolution vs. the effect on CPU time.

**Comment by kelseymh** [comment]
> it looks like there was a git add that included a build directory. Is there a way to cherry pick that out? It's not too big, really.
> --it looks like the merge of feature/14 included the build directory of RTD

If we don't want the build/ directory in the repository, could you attach a specific comment to it as part of this review?  The method would be to simply use `git rm` and commit that change.

**Pull request merged**
